name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@master
        env:
          CT_CHECK_VERSION_INCREMENT: "false"
        with:
          command: lint
          config: .github/ct.yaml

#  lint-docs:
#    runs-on: ubuntu-latest
#    needs: lint-chart
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Run helm-docs
#        run: .github/helm-docs.sh

  deprecation-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: curl
          uses: wei/curl@master
          with:
            args: https://raw.githubusercontent.com/naquada/deprek8/master/policy/deprek8.rego > /github/home/deprek8.rego
        - name: Check helm chart for deprecation
          uses: instrumenta/conftest-action/helm@master
          with:
            chart: charts/oci-service-broker/
            policy: /github/home/deprek8.rego
  
  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    #  - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.14.8
          - v1.15.7
          - v1.16.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    #  - lint-docs
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.14.9
          - v1.15.7
          - v1.16.9
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@master
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Create dummy credential secret
        run: |
          kubectl create secret generic oci-credentials \
          --from-literal=tenancy=ocid1.tenancy.oc1..aaaa... \
          --from-literal=user=ocid1.user.oc1..aaaa... \
          --from-literal=region=us-ashburn-1 \
          --from-literal=fingerprint=00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:f0 \
          --from-literal=passphrase=changeme \
          --from-file=privatekey=.github/ct.yaml
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@master
        with:
          command: install --debug
          config: .github/ct.yaml
